### ISSUE TITLE
Setup simple network error

### ISSUE THREAD

**Issue by thapld** [hyfen-eu/PIVT#113]
![image](https://github.com/hyfen-eu/PIVT/assets/38736191/c28377e8-fc2c-4ad8-aca8-23cd1c6df8ac)

**Comment by raftAtGit** [comment]
it might be another yq. it just works here. try installing yq with pip as mentioned in the requirements section

```
 yq --version
yq 3.2.2
```

**Comment by thapld** [comment]
Thank you.
Can you make more tutorial or youtube video about your sdk?

**Comment by raftAtGit** [comment]
not really. there is more than enough documentation in this repo (as stated by others too)

**Comment by thapld** [comment]
And it's ready for production, right?

**Comment by raftAtGit** [comment]
it was intended to be production ready and used in production for a long time.

**Comment by thapld** [comment]
Thank you so much.
